### ISSUE TITLE
composer install not passing without api key in .env

### ISSUE THREAD

**Issue by janmedilek** [matt-oakes/PHP-Last.fm-API#22]
Hi Matt,
when I use deployer while using your repository "composer install" command fails with:
 [LastFmApi\Exception\InvalidArgumentException]                               
  Must send an apiKey, secret, usernamne, subcriber and sessionKey in the call for setsession

Temporary solution is setting LASTFM_API_KEY variable in .env file. 
My guess is that it commes from one of tests. Do tests require any value set in .env file?

**Comment by devilcius** [comment]
Hi Jan,

I guess you a have a script defined in your composer.json to run the tests? These are integration tests and need the variables set in the .env file. If you want them to be run, you must fill each of the variable values. I'll update the README file to show how to do it.

**Comment by janmedilek** [comment]
Ah ok. Thanks :)
