### ISSUE TITLE
cannot manage to make it scrobble

### ISSUE THREAD

**Issue by gordielachance** [matt-oakes/PHP-Last.fm-API#23]
Hi guys, and thanks for this nice library !!!

I just implemented it in my Wordpress plugin, [WP Soundsystem](https://github.com/gordielachance/wp-soundsystem).

Almost everything works except that I can't manage to make it scrobble.

I have the **updateNowPlaying()** calls working (called when track starts), it shows up on my Last.FM profile as _Scrobbling now_.
Then when the track has finished playing,  I call **scrobble()**.
But the track do not show up in my Last.FM library :/

Here's an example of what I set as arguments for the **scrobble()** function (it's a json from my debug log)

`{"artist":"Ice Cube","track":"Man s Best Friend","timestamp":"1495026495897","album":null,"chosenByUser":0,"duration":"126"}`

I also did try to unset _chosenByUser_ but it does not change anything.

You can check the code [here](https://github.com/gordielachance/wp-soundsystem/blob/master/wpsstm-core-lastfm.php#L518) and see it in action [there](http://www.spiff-radio.org/).

Thanks a lot !!!

**Comment by devilcius** [comment]
I've just added a test for the track scrobble method 46765fff2cad0ae63419cf82c3ba680b2d8a9e95. It's working for me. Note that sometimes last.fm takes a while to update the data. Also the response is just a boolean (not as described in their API documentation).

The test uses PHP's `time()` to get the UNIX timestamp, you're using jQuery's  `$.now()` (a shorthand for javascript's `(new Date).getTime()`. Javascript returns the timestamp in milleseconds, but according to the LastFm API documentation it's expecting only the seconds:
>UNIX timestamp format (integer number of seconds since 00:00:00, January 1st 1970 UTC)

Maybe that could be the problem. Use `Math.floor(Date.now() / 1000)` to remove the milliseconds o just refactor a little bit and set the timestamp in _wpsstm-core-lastfm.php_ with `time()`

Nice plugin, by the way. Congrats.

**Comment by gordielachance** [comment]
Hi @devilcius !  
You were right, the problems was that I used milliseconds.
Thanks a lot, it's working now !!!
