### ISSUE TITLE
Hi, how can I check that the user is successully logged ?

### ISSUE THREAD

**Issue by gordielachance** [matt-oakes/PHP-Last.fm-API#35]
Hi, after I call

`$user_auth = new AuthApi('setsession', $auth_args);`

How can I check that the user is successfully logged ?
Thanks for your work !

**Comment by devilcius** [comment]
It depends, if you only pass the _apiKey_ in the arguments the user is not authenticated. You get authorization to make not authenticated api calls.
If you want an authenticated session you have to pass other arguments. You have an example in `Tests\Api\AuthenticatedTrackTest`
